# CustomDecentHolograms v1.1 configuration file
# Report bugs and issues at vanted.net/discord
#
# hologram:
#   apis:
#     - GriefPrevention
#     - WorldGuard
#   region: Only needed if using WorldGuard as API option
#   max-lines: Limit the maximum lines a hologram can have
#   max-characters: Limit the maximum characters on each line
#   spawn-lines: Set the display for new holograms
#   spawn-location: Set the location for new holograms
#
# Assign cdh.amount.<number> permissions to groups and/or players
# This will allow them to create x number of holograms themselves

hologram:
  api: ""
  region: ""
  max-lines: 6
  max-characters: 40
  spawn-lines:
    - "&u&l{0}'s Hologram"
    - "&fEdit lines &7» &a/hg edit <hologram> <line>"
    - "&fAdd lines &7» &a/hg add <hologram> <text>"
    - "&fRemove lines &7» &a/hg remove <hologram> <line>"
    - "&fList all of your owned holograms &7» &a/hg list"
    - "&fUse colors and floating items &7» &a/hg formats"
  spawn-location:
    world: world
    x: 0
    y: 0
    z: 0